Addition of Dockerfiles
Thogarf/go-exercise pull request #11
Opened 2022-10-10 23:16 UTC by ad3m3r5

This PR introduces alpine and distroless versions of Dockerfiles. Both use the golang:1.19-alpine image for building the project, while packaging it in either of the aforementioned options.

Buildable using the commands:
alpine: `docker build -t go-exercise -f Dockerfile.alpine .`
distroless: `docker build -t go-exercise -f Dockerfile.distroless.`

2022-10-10 23:39 UTC, Thogarf requested changes

2022-10-10 23:39 UTC, Thogarf commented on Dockerfile.alpine
> +FROM alpine:3.16
Since the only thing differing between the two files is the final container base image, I think we should consolidate this to one file, add an `ARG` to accept the distro via the command line, and default to `distroless`. Thoughts?

2022-10-11 02:53 UTC, ad3m3r5 commented on Dockerfile.alpine
> +FROM alpine:3.16
This is a good idea. I have implemented this in b6a4156 with the `BASE_IMAGE` build-arg, which defaults to the latest `gcr.io/distroless/static` image.

Build Behavior:
default / distroless (static): `docker build -t go-exercise -f Dockerfile .`
other (example): `docker build --build-arg BASE_IMAGE=alpine:3.15.6 -t go-exercise:alpine-3.15.6 -f Dockerfile .`

For comparison:
`go-exercise:distroless`: 4.16 MB
`go-exercise:alpine`: 7.35 MB

2022-10-13 16:54 UTC, Thogarf approved these changes
Looks good to me, thanks!

2022-10-13 16:55 UTC, merged